# Debug mode
# This will log in console when storms are forced stopped or cancelled
debug: false

# Maximum rain duration (in seconds)
# Default 300 (5 minutes)
maxDurationOfStorms: 300

# Minimum duration between storms (in seconds)
# Default 1800 (30 minutes)
minDurationBetweenStorms: 1800

# List of worlds that you do not want to restrict rain on (CaSe SeNsItIvE)
excludedWorlds: 
- world_nether
- world_the_end
