name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
author: BillyGalbreath
description: ${project.artifactId} Bukkit Plugin

commands:
  lessrain:
    description: Reload config
    permissions: command.lessrain
    usage: /<command> reload

permissions:
    command.lessrain:
        description: Reload config
        default: op
